using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orders.Domain;

namespace Orders.Api.Persistence.Conversions;

// Registered once, by CLR type, in OrdersDbContext.ConfigureConventions (ADR-0003) —
// not property by property. Each id is stored as uuid; the domain creates the value
// (OrderId.New(), etc.), so it is never generated by the database.

internal sealed class OrderIdConverter() : ValueConverter<OrderId, Guid>(id => id.Value, value => new OrderId(value));

internal sealed class CustomerIdConverter() : ValueConverter<CustomerId, Guid>(id => id.Value, value => new CustomerId(value));

internal sealed class ProductIdConverter() : ValueConverter<ProductId, Guid>(id => id.Value, value => new ProductId(value));
